// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADjG1WAIP4M8gS-mKB1iVrOoFmkGASCtU',
    appId: '1:1095889076649:web:418f500bec5bb2215784b8',
    messagingSenderId: '1095889076649',
    projectId: 'quotes2-a5cd1',
    authDomain: 'quotes2-a5cd1.firebaseapp.com',
    storageBucket: 'quotes2-a5cd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OVE4mB2itLiNcHGCey21NxMt3JYo_HQ',
    appId: '1:1095889076649:android:65b3529c65ff5afe5784b8',
    messagingSenderId: '1095889076649',
    projectId: 'quotes2-a5cd1',
    storageBucket: 'quotes2-a5cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClQPQGh8fGu4h5nBjVsC3Kzc7YXFjDO-M',
    appId: '1:1095889076649:ios:24d0b81997be2b1c5784b8',
    messagingSenderId: '1095889076649',
    projectId: 'quotes2-a5cd1',
    storageBucket: 'quotes2-a5cd1.appspot.com',
    iosBundleId: 'com.example.quotes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClQPQGh8fGu4h5nBjVsC3Kzc7YXFjDO-M',
    appId: '1:1095889076649:ios:24d0b81997be2b1c5784b8',
    messagingSenderId: '1095889076649',
    projectId: 'quotes2-a5cd1',
    storageBucket: 'quotes2-a5cd1.appspot.com',
    iosBundleId: 'com.example.quotes2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADjG1WAIP4M8gS-mKB1iVrOoFmkGASCtU',
    appId: '1:1095889076649:web:9890c6d95b7a87fe5784b8',
    messagingSenderId: '1095889076649',
    projectId: 'quotes2-a5cd1',
    authDomain: 'quotes2-a5cd1.firebaseapp.com',
    storageBucket: 'quotes2-a5cd1.appspot.com',
  );
}
